spring.application.name=backend

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/erp
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=dweqidjr348239nejwfnbwdvb294y8f3cndsbve27fyh32fejfbewuify283fbdjvcbsdhjv2e78ry32rbhefdbe8gf2hjbsifgh2efefgyew7rf233hbrfy23itrg3